// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductListApp.Data;

#nullable disable

namespace ProductListApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductListApp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("RatingCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Graphic t-shirt with colorful rainbow pattern",
                            ImageUrl = "/images/gradient-tshirt.jpg",
                            Name = "Gradient Graphic T-shirt",
                            Price = 145m,
                            Quantity = 25,
                            Rating = 3.8999999999999999,
                            RatingCount = 5
                        },
                        new
                        {
                            Id = 2,
                            Description = "Classic polo shirt with contrast tipping",
                            ImageUrl = "/images/polo-tipping.jpg",
                            Name = "Polo with Tipping Details",
                            Price = 180m,
                            Quantity = 30,
                            Rating = 4.5,
                            RatingCount = 6
                        },
                        new
                        {
                            Id = 3,
                            Description = "Striped t-shirt with raglan sleeves",
                            ImageUrl = "/images/black-striped-tshirt.jpg",
                            Name = "Black Striped T-shirt",
                            OriginalPrice = 160m,
                            Price = 120m,
                            Quantity = 20,
                            Rating = 5.0,
                            RatingCount = 7
                        },
                        new
                        {
                            Id = 4,
                            Description = "Skinny fit stretch denim jeans",
                            ImageUrl = "/images/skinny-jeans.jpg",
                            Name = "Skinny Fit Jeans",
                            OriginalPrice = 260m,
                            Price = 240m,
                            Quantity = 15,
                            Rating = 3.5,
                            RatingCount = 5
                        },
                        new
                        {
                            Id = 5,
                            Description = "Classic checkered pattern long sleeve shirt",
                            ImageUrl = "/images/checkered-shirt.jpg",
                            Name = "Checkered Shirt",
                            Price = 180m,
                            Quantity = 18,
                            Rating = 4.5999999999999996,
                            RatingCount = 7
                        },
                        new
                        {
                            Id = 6,
                            Description = "Orange striped t-shirt with contrast sleeves",
                            ImageUrl = "/images/sleeve-striped-tshirt.jpg",
                            Name = "Sleeve Striped T-shirt",
                            OriginalPrice = 160m,
                            Price = 130m,
                            Quantity = 22,
                            Rating = 4.5,
                            RatingCount = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Vertical striped long sleeve button-up shirt",
                            ImageUrl = "/images/vertical-striped-shirt.jpg",
                            Name = "Vertical Striped Shirt",
                            OriginalPrice = 232m,
                            Price = 212m,
                            Quantity = 12,
                            Rating = 5.0,
                            RatingCount = 8
                        },
                        new
                        {
                            Id = 8,
                            Description = "Orange graphic t-shirt with printed design",
                            ImageUrl = "/images/courage-tshirt.jpg",
                            Name = "Courage Graphic T-shirt",
                            Price = 145m,
                            Quantity = 20,
                            Rating = 4.0,
                            RatingCount = 5
                        },
                        new
                        {
                            Id = 9,
                            Description = "Classic denim bermuda shorts",
                            ImageUrl = "/images/bermuda-shorts.jpg",
                            Name = "Loose Fit Bermuda Shorts",
                            Price = 80m,
                            Quantity = 25,
                            Rating = 3.0,
                            RatingCount = 5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
